:- module(domain_registry, [domain_category/2]).
% --- AUTOMATICALLY GENERATED DOMAIN REGISTRY ---
% Thresholds aligned with config.pl: Rope <= 0.15, Snare >= 0.46, Tangled Rope 0.16-0.9.
% Total entries: 999

domain_category(absorbing_markov_chains, mountain).
domain_category(abstraction_boundary_overrun, snare).
domain_category(academic_fashion_modernism_2026, snare).
domain_category(academic_peer_review_gatekeeping, snare).
domain_category(academic_tenure_system, snare).
domain_category(access_arbitrage, snare).
domain_category(acip_hep_b_infant_mandate, rope).
domain_category(ad_fus_coordination, tangled_rope).
domain_category(ad_synaptic_deficit, snare).
domain_category(adaptive_lag_trap, snare).
domain_category(adversarial_surface_inflation, snare).
domain_category(adversarial_truth_decay, snare).
domain_category(advice_as_dangerous_gift, snare).
domain_category(agentive_optimism_2026, snare).
domain_category(agg1_genetic_determinism, snare).
domain_category(aging_well_assessment, snare).
domain_category(ai_adoption_stigma, snare).
domain_category(ai_auditability_gap, snare).
domain_category(ai_banal_capture, snare).
domain_category(ai_driven_surveillance_sensor_layer, snare).
domain_category(ai_evaluators_matching, snare).
domain_category(ai_performance_watermark, snare).
domain_category(ai_professional_displacement, snare).
domain_category(ai_religion_regulation, snare).
domain_category(ai_scholar_citation_trap, snare).
domain_category(ai_superpowers_race_2026, snare).
domain_category(ai_task_horizon_reliability, snare).
domain_category(ai_training_data_dependency, snare).
domain_category(airport_slot_use_it_or_lose_it, snare).
domain_category(algeria_france_colonial_legacy, snare).
domain_category(algorithmic_bias, snare).
domain_category(algorithmic_epistemic_capture, snare).
domain_category(alignment_tax_tradeoff, snare).
domain_category(allocation_as_extraction_multiplier, snare).
domain_category(allusive_density_as_exclusion, snare).
domain_category(alternative_sovereignty_scaffold, scaffold).
domain_category(altruistic_misery_paradox_2026, snare).
domain_category(alzheimers_drug_approval_timeline, snare).
domain_category(alzheimers_levetiracetam, snare).
domain_category(amish_technological_renunciation, snare).
domain_category(ancestral_pueblo_hydrology, snare).
domain_category(ancient_grudge_verona, snare).
domain_category(anticipatory_capacity_failure, snare).
domain_category(antifragility, rope).
domain_category(antikythera_knowledge_loss, snare).
domain_category(apartheid_nuclear_program, snare).
domain_category(ape_cognition_framework, snare).
domain_category(appropriations_brinkmanship, snare).
domain_category(arbitrary_enforcement_extraction, snare).
domain_category(architectural_constraint_as_dual_substrate, mountain).
domain_category(arctic_geopolitical_flashpoint, snare).
domain_category(arg_ev_tariff, snare).
domain_category(armra_colostrum_regulation, snare).
domain_category(arrows_impossibility_theorem, snare).
domain_category(artificial_scarcity_scaffold, scaffold).
domain_category(artificial_snow_2026, snare).
domain_category(asean_ceasefire_2011, snare).
domain_category(asshole_filter_2015, snare).
domain_category(asymmetric_burden_distribution, snare).
domain_category(asymmetric_computational_difficulty, snare).
domain_category(asymmetric_coordination_extraction, snare).
domain_category(asymmetric_duty_structure, snare).
domain_category(atrophied_optimization_piton, piton).
domain_category(attention_as_bottleneck_resource, snare).
domain_category(attention_as_capturable_resource, mountain).
domain_category(attention_market_cannibalization, snare).
domain_category(attribution_ambiguity_triplet_sc, tangled_rope).
domain_category(attritional_warfare_doctrine_ru_ua_2026, snare).
domain_category(au_social_media_ban_u16, snare).
domain_category(australia_social_ban_2026, snare).
domain_category(authoritarian_power_paradox, snare).
domain_category(automatic_enrollment_defaults, tangled_rope).
domain_category(availability_heuristic, snare).
domain_category(average_is_over_2026, snare).
domain_category(awareness_without_leverage, snare).
domain_category(axiom_of_choice_determinacy, mountain).
domain_category(axiom_reasoner_2026, snare).
domain_category(banach_fixed_point, mountain).
domain_category(banach_fixed_point_theorem, mountain).
domain_category(banach_tarski_paradox, mountain).
domain_category(bangladesh_july_national_charter, snare).
domain_category(base_pair_complementarity, mountain).
domain_category(basel_problem_convergence, mountain).
domain_category(bayes_theorem, snare).
domain_category(bedouin_sedentary_transition, snare).
domain_category(beehiiv_platform_model, snare).
domain_category(belief_argument_conclusion, snare).
domain_category(berkshire_compounding_culture, tangled_rope).
domain_category(bgs_eigenvector_thermalization, tangled_rope).
domain_category(bgs_spectral_universality, mountain).
domain_category(bh_merger_gravitational_infall, mountain).
domain_category(big_data_astrophysics_arbitrage, snare).
domain_category(biological_specification, tangled_rope).
domain_category(bip_narrative_illusion, snare).
domain_category(birthday_paradox_collison, mountain).
domain_category(blackstone_carried_interest_taxation, snare).
domain_category(blackstone_conflicts_of_interest, snare).
domain_category(blackstone_smd_control, snare).
domain_category(blackstone_tax_receiveable_agreement, tangled_rope).
domain_category(board_of_peace_2026, snare).
domain_category(boe_base_rate_policy_2024, snare).
domain_category(boiled_pineapple_trend_2026, piton).
domain_category(boltzmann_universality_2026, mountain).
domain_category(bonbon_drop_sticker_craze, snare).
domain_category(boom_bust_path_dependency, piton).
domain_category(borsuk_ulam_theorem, mountain).
domain_category(boundary_dissolution_risk, snare).
domain_category(brain_network_paradigm_2026, tangled_rope).
domain_category(brazil_2026_general_elections, snare).
domain_category(brazil_hiv_vtn_elimination, rope).
domain_category(brazil_mexico_financial_requirement, snare).
domain_category(brilliance_as_structural_liability, snare).
domain_category(brilliance_as_structural_trap, snare).
domain_category(broke_vs_poor_grocery_math, snare).
domain_category(brouwer_fixed_point, mountain).
domain_category(burali_forte_paradox, mountain).
domain_category(burden_of_proof_engineering_safety, snare).
domain_category(burden_of_proof_scientific_empirical, snare).
domain_category(bureaucratic_accommodation_as_extraction_persistence, snare).
domain_category(bureaucratic_legibility_collapse, snare).
domain_category(bureaucratic_self_preservation, snare).
domain_category(bushman_money_magic, snare).
domain_category(busy_beaver_noncomputability, mountain).
domain_category(bwb_adeg_rewesale_conditions, snare).
domain_category(c_physical_blue_wavelength, mountain).
domain_category(canada_germany_ai_pact, tangled_rope).
domain_category(canal_panama_influence, snare).
domain_category(cancer_chronotherapy_timing, tangled_rope).
domain_category(cancer_prevention, snare).
domain_category(cantor_set_topology, mountain).
domain_category(cantors_diagonal_argument, mountain).
domain_category(cap_theorem, mountain).
domain_category(capability_compulsion_gradient, mountain).
domain_category(capability_eval_overhang, snare).
domain_category(capital_misallocation_spiral, snare).
domain_category(capital_rotation_ai_narrative, snare).
domain_category(car_ownership_norm_us, snare).
domain_category(carbon_credit_markets_2026, snare).
domain_category(carrier_deployment_deterrence, snare).
domain_category(carrying_capacity, snare).
domain_category(cartel_drone_surveillance_el_paso, snare).
domain_category(cascading_constraint_failure, snare).
domain_category(castration_longevity_choice, tangled_rope).
domain_category(categorical_boundary_as_cognitive_load_limiter, rope).
domain_category(categorical_instrument_blindness, rope).
domain_category(categorical_violence_as_structural_exclusion, rope).
domain_category(cb_far_beyond_human, snare).
domain_category(cbdc_implementation, snare).
domain_category(central_limit_theorem_convergence, mountain).
domain_category(centralized_digital_identity, snare).
domain_category(cfius_hiefo_emcore_divestment, snare).
domain_category(cg_israelgaza_20231012, snare).
domain_category(chaitins_omega_undecidability, mountain).
domain_category(champions_bass_fishing_exclusion, snare).
domain_category(china_africa_zero_tariff_2026, snare).
domain_category(china_contraceptive_tax, snare).
domain_category(china_vactrain_standard, snare).
domain_category(cholesterol_pill_cost, snare).
domain_category(church_turing_thesis, mountain).
domain_category(cinderella_midnight_deadline, snare).
domain_category(civilizational_lifecycle_solara, tangled_rope).
domain_category(civilizational_maintenance_debt, snare).
domain_category(clarification_loop_structure, tangled_rope).
domain_category(clawderberg_recursive_slop, snare).
domain_category(click_chemistry_paradigm_2026, tangled_rope).
domain_category(climate_attribution_2026, snare).
domain_category(climate_catastrophe_belief, snare).
domain_category(climate_event_attribution, snare).
domain_category(climate_policy_extraction, snare).
domain_category(climate_target_one_point_five, snare).
domain_category(cloudflare_dual_class_asymmetry, snare).
domain_category(clt_convergence_2026, mountain).
domain_category(cmr_001, snare).
domain_category(cn_tech_decoupling_security_software, snare).
domain_category(cobra_effect, snare).
domain_category(codex_access, snare).
domain_category(coe_ukraine_reparations_register, snare).
domain_category(coffee_cardiovascular_2026, tangled_rope).
domain_category(cognitive_bicycle_scaffold, scaffold).
domain_category(cognitive_diversity_arbitrage, snare).
domain_category(cognitive_energy_budget, snare).
domain_category(cognitive_hacking_2026, snare).
domain_category(cognitive_induction_gap, snare).
domain_category(cognitive_surrender_to_system_3, snare).
domain_category(coinbase_crypto_volatility, snare).
domain_category(cold_dark_matter_paradigm, snare).
domain_category(collatz_conjecture_determinism, mountain).
domain_category(collective_action_as_leverage_conversion, rope).
domain_category(collective_action_blockage_via_stratification, snare).
domain_category(collective_action_deadlock, snare).
domain_category(collective_action_threshold, scaffold).
domain_category(collective_stupidity_2026, snare).
domain_category(college_admissions_market, snare).
domain_category(colorado_sbe_decentralization_friction, snare).
domain_category(colossus_nero_inertia, snare).
domain_category(columbia_2026_elections, snare).
domain_category(comitatus_bond, tangled_rope).
domain_category(commercial_data_brokerage, snare).
domain_category(communal_narcissism_social_trap, snare).
domain_category(complexity_debt, snare).
domain_category(complicity_through_competence, snare).
domain_category(compounding_obligation_trap, snare).
domain_category(condiment_tyranny, tangled_rope).
domain_category(confidential_ai_whatsapp, snare).
domain_category(confirmation_bias, snare).
domain_category(consensus_without_truth, snare).
domain_category(constitutional_supremacy, tangled_rope).
domain_category(constraint_coupling_amplification, snare).
domain_category(consumer_debt_slavery, snare).
domain_category(continuum_hypothesis_undecidability, mountain).
domain_category(conversational_dogmas_interuption, snare).
domain_category(conways_game_of_life_dynamics, mountain).
domain_category(coordination_attack_vulnerability, snare).
domain_category(coordination_barrier_topology, mountain).
domain_category(coordination_extraction_invisibility, snare).
domain_category(coordination_failure_universality, snare).
domain_category(coordination_fatigue, snare).
domain_category(coordination_threshold_failure, tangled_rope).
domain_category(copyleft_viral_licensing, tangled_rope).
domain_category(copyright_protection, snare).
domain_category(cosmological_evolution_alpha_omega, mountain).
domain_category(cost_of_observation, tangled_rope).
domain_category(countable_infinity_cardinality, mountain).
domain_category(couples_residency_match, tangled_rope).
domain_category(cow_field_poop, rope).
domain_category(credibility_inflation, snare).
domain_category(crisis_signal_saturation, snare).
domain_category(crispr_genomic_rewrite_2026, tangled_rope).
domain_category(critical_actor_overcentralization, snare).
domain_category(crop_defense_dependency, snare).
domain_category(cross_domain_coupling_spiral, snare).
domain_category(cuba_mandatrophic_collapse, snare).
domain_category(cuban_missile_crisis_excomm_delibration, tangled_rope).
domain_category(cultural_homogenization_social_media, snare).
domain_category(cultural_memory_decay, snare).
domain_category(cultural_refragmentation_2026, snare).
domain_category(cumbria_mine_rejection, snare).
domain_category(cuny_light_2026, rope).
domain_category(currys_paradox, mountain).
domain_category(damped_harmonics, mountain).
domain_category(dark_patterns_manipulation, snare).
domain_category(data_laundering_pipeline, snare).
domain_category(data_privacy_regulation, snare).
domain_category(dead_sea_effect, snare).
domain_category(debt_leverage_as_consent_manufacturing, tangled_rope).
domain_category(debt_service_squeeze, snare).
domain_category(debt_trap_compounding, snare).
domain_category(debt_trap_microfinance, snare).
domain_category(decapitation_as_regime_change, snare).
domain_category(decision_latency_mismatch, snare).
domain_category(deep_earth_hydrogen_availability, mountain).
domain_category(deferential_realism_core, snare).
domain_category(deferred_risk_realization, snare).
domain_category(degraded_deterrence_architecture, mountain).
domain_category(delayed_feedback_instability, snare).
domain_category(delta_force_selection_2026, snare).
domain_category(demand_response_cost_shift, snare).
domain_category(demographic_inertia_trap, snare).
domain_category(denmark_asylum_outsourcing, snare).
domain_category(devotional_transformation, tangled_rope).
domain_category(digital_credentialing_verification, snare).
domain_category(digital_euro_cbdc, snare).
domain_category(digital_identity_tether, snare).
domain_category(dionysaic_frenzy, snare).
domain_category(discover_core_2026, snare).
domain_category(disney_openai_ip_exclusivity, snare).
domain_category(distributed_memory_as_counter_disposal, snare).
domain_category(dk_foreign_convict_expulsion, snare).
domain_category(dldr_information_policy, snare).
domain_category(documentation_fidelity_collapse, snare).
domain_category(doomsday_clock_framework, snare).
domain_category(drc_rwanda_peace_deal_2024, snare).
domain_category(dunning_kruger_effect, tangled_rope).
domain_category(dutch_minority_govt_2026, snare).
domain_category(duty_contamination_by_extraction, snare).
domain_category(dwp_carers_allowance_cliff, snare).
domain_category(e2ee_digital_privacy_2026, snare).
domain_category(ec_meta_manus_block, snare).
domain_category(edelman_2026_developing_volatility, snare).
domain_category(edelman_2026_insularity, snare).
domain_category(educational_unbundling_implementation, snare).
domain_category(ehrenfest_barrier, mountain).
domain_category(elencher_identity_transformation, snare).
domain_category(elite_capture_2026, snare).
domain_category(elite_identity_capture_2026, snare).
domain_category(elite_overproduction_instability, snare).
domain_category(elliq_ai_companion, snare).
domain_category(emergency_oversight_bureau, scaffold).
domain_category(emergency_powers_ratchet, snare).
domain_category(emergent_goal_misalignment, snare).
domain_category(emotional_cycles_of_change, tangled_rope).
domain_category(empty_tomb_transformation, snare).
domain_category(endocrine_disruption_society, snare).
domain_category(enforcement_gap_exploitation, rope).
domain_category(english_chinese_tense_structure, tangled_rope).
domain_category(environmental_instability_as_constraint, mountain).
domain_category(epigenetics_complexity_2026, tangled_rope).
domain_category(epistemic_authority_erosion_through_unresolvable_anomaly, snare).
domain_category(epistemic_free_rider_problem, snare).
domain_category(epistemic_irreducibility_mountain, mountain).
domain_category(epistemic_overload_collapse, snare).
domain_category(epistemic_process_of_verification, rope).
domain_category(epstein_document_release_2026, snare).
domain_category(epstein_files_2026, snare).
domain_category(erasmus_rejoining_scaffold, scaffold).
domain_category(ergo_autolykos_asic_resistance, snare).
domain_category(ergo_dexy_gold_protocol, snare).
domain_category(ergo_lets_protocol, rope).
domain_category(ergo_nipopows, tangled_rope).
domain_category(ergo_rosen_bridge_protocol, tangled_rope).
domain_category(ergo_storage_rent, tangled_rope).
domain_category(ergo_storage_rent_mechanism, tangled_rope).
domain_category(ergodic_theorems, tangled_rope).
domain_category(error_induced_stability, snare).
domain_category(escalation_control_asymmetry, snare).
domain_category(eu_affordable_housing_initiative, snare).
domain_category(eu_deforestation_regulation, snare).
domain_category(eu_digital_services_act, snare).
domain_category(eu_irgc_terrorist_designation, snare).
domain_category(eu_renewable_energy_mandate, snare).
domain_category(eu_russian_asset_freeze_2025, snare).
domain_category(eu_unanimity_rule_foreign_policy, snare).
domain_category(euler_characteristic_topology, mountain).
domain_category(eurozone_fragmentation_2026, snare).
domain_category(evidence_half_life, snare).
domain_category(evolutionary_knowledge, tangled_rope).
domain_category(evolutionary_mismatch_load, snare).
domain_category(exclusion_as_preparation, rope).
domain_category(exclusionary_coordination_asymmetry, snare).
domain_category(exoplanet_habitability_arbitrage, tangled_rope).
domain_category(expert_disempowerment, snare).
domain_category(exploration_vs_exploitation, snare).
domain_category(extraction_residue_as_bodily_inscription, mountain).
domain_category(extraordinary_narrative_shift, snare).
domain_category(faint_blue_neural_bifurcation, snare).
domain_category(false_mountain_naturalization, snare).
domain_category(false_mountain_persistence, snare).
domain_category(family_estrangement_ratio, snare).
domain_category(family_succession_and_decadence, snare).
domain_category(fast_growing_hierarchy, mountain).
domain_category(fatf_grey_list_russia, snare).
domain_category(fb_creator_monetization_indonesia, snare).
domain_category(fcc_dji_covered_list, snare).
domain_category(fda_accelerated_approval_alz, snare).
domain_category(fda_component_efficacy_standard, tangled_rope).
domain_category(fda_gonorrhea_efficacy_standard, snare).
domain_category(fed_shutdown_2026, snare).
domain_category(feigenbaum_universality, mountain).
domain_category(fermats_last_theorem, mountain).
domain_category(fgh_hierarchy_2026, mountain).
domain_category(fiat_currency_lifecycle, snare).
domain_category(financialization_drag, snare).
domain_category(finite_pool_of_worry, tangled_rope).
domain_category(finite_simple_groups_classification, mountain).
domain_category(finnish_debt_adjustment, tangled_rope).
domain_category(finnish_ubi_experiment, snare).
domain_category(fiscal_dominance_trap, snare).
domain_category(fiscal_equalization_friction, tangled_rope).
domain_category(floating_wall_2026, snare).
domain_category(fmeca_procedures_1980, tangled_rope).
domain_category(fmt_oncology_realignment_2026, snare).
domain_category(fnl_shadow_probe, tangled_rope).
domain_category(formalization_translation_rope, rope).
domain_category(four_color_theorem_topological_bound, mountain).
domain_category(fptp_electoral_system, snare).
domain_category(fragile_middle_layer_collapse, snare).
domain_category(fragmentation_as_arbitrage, snare).
domain_category(france_cordon_sanitaire_2026, piton).
domain_category(franchisee_corporate_squeeze, snare).
domain_category(frankenstein_creation_hubris, snare).
domain_category(fraser_river_salmon_regulation, snare).
domain_category(french_ag_land_concentration, snare).
domain_category(french_local_elections_march_2026, scaffold).
domain_category(friction_as_intervention_medium, rope).
domain_category(fundamental_material_limits_nbre, mountain).
domain_category(fundamental_theorem_of_algebra, mountain).
domain_category(fundamental_theorem_of_calculus, mountain).
domain_category(fungal_shift_grassland_loss, snare).
domain_category(fused_quartz_5d_archival, rope).
domain_category(future_dsm_integration_2026, snare).
domain_category(g7_debt_trap, snare).
domain_category(gale_shapley, tangled_rope).
domain_category(galois_theory, mountain).
domain_category(galois_theory_symmetry, mountain).
domain_category(gauss_bonnet_topology, mountain).
domain_category(gaza_aid_permit_revocation, snare).
domain_category(gaza_border_control_rafah, snare).
domain_category(gbff_funding_mechanism, snare).
domain_category(gemini_scientific_advancement, snare).
domain_category(genai_mil_platform, snare).
domain_category(genetic_algorithms_evolution, rope).
domain_category(genetic_predisposition, snare).
domain_category(geophysics_superionic_core, mountain).
domain_category(geopolitical_insularity_2026, snare).
domain_category(german_board_gender_quota, tangled_rope).
domain_category(germany_tennet_takeover, tangled_rope).
domain_category(germline_regulation_threshold_2026, snare).
domain_category(gilgamesh_mortality_limit, mountain).
domain_category(gita_kurukshetra, snare).
domain_category(global_economic_anxiety_2026, snare).
domain_category(global_food_market_fragility, snare).
domain_category(global_hoarding_scaling_laws, snare).
domain_category(global_protocol_entrenchment, snare).
domain_category(global_stimulus_spree, snare).
domain_category(global_water_bankruptcy, snare).
domain_category(glp1_payload_efficiency_pivot, tangled_rope).
domain_category(goal_boundary_poisoning, snare).
domain_category(godels_incompleteness_theorems, mountain).
domain_category(gold_fomo_cycle, snare).
domain_category(gold_piton_2026, piton).
domain_category(goldbach_conjecture, mountain).
domain_category(golden_handcuffs, snare).
domain_category(goodharts_law, snare).
domain_category(google_ai_search_overview, snare).
domain_category(google_universal_commerce_protocol, snare).
domain_category(governance_latency_gap, snare).
domain_category(governance_overfitting, snare).
domain_category(gpt5_codex_dev_cycle, snare).
domain_category(gpt_store_marketplace, snare).
domain_category(gravitational_lensing_cosmic_dawn, mountain).
domain_category(great_mongolian_road_economic_dependency, snare).
domain_category(greenland_defence_pact_2026, snare).
domain_category(greenland_seizure_trade_war, snare).
domain_category(greshams_law, tangled_rope).
domain_category(grete_samsa_transition, snare).
domain_category(grievance_stack_overflow, snare).
domain_category(gs1_gln_identification, tangled_rope).
domain_category(guano_wealth_extraction, snare).
domain_category(guinea_worm_eradication, rope).
domain_category(hagia_sophia_status, snare).
domain_category(halting_problem_undecidability, mountain).
domain_category(hamiltonian_path_complexity, mountain).
domain_category(hanlons_razor, snare).
domain_category(happiness_of_others, snare).
domain_category(harlequin_historical_line_discontinuation, snare).
domain_category(harry_potter_liberalism, snare).
domain_category(hasbro_licensing_restriction, snare).
domain_category(hawthorne_effect, tangled_rope).
domain_category(hd101584_stellar_evolution, mountain).
domain_category(hegemonic_entropy_2026, snare).
domain_category(heine_borel_theorem, mountain).
domain_category(heisenberg_uncertainty, mountain).
domain_category(help_to_buy_uk, snare).
domain_category(helsinki_bus_theory, snare).
domain_category(hershey_salt_strategy, snare).
domain_category(heuristic_optimization, tangled_rope).
domain_category(hhs_fetal_tissue_research_ban_2019, snare).
domain_category(hicbc_uk, tangled_rope).
domain_category(hilberts_hotel, mountain).
domain_category(hilberts_hotel_infinity, mountain).
domain_category(hiv_prep_prevention_2026, tangled_rope).
domain_category(hk_nsl_civic_party_disbandment, snare).
domain_category(hoa_covenants, snare).
domain_category(hominin_evolutionary_bottleneck, tangled_rope).
domain_category(horizon_liability_contract, snare).
domain_category(hormuz_leverage_paradox, snare).
domain_category(hu_2026_electoral_parity, tangled_rope).
domain_category(huang_expectation_resilience_2026, snare).
domain_category(hub_short_form_tv_market_fragmentation, snare).
domain_category(hydra_game, mountain).
domain_category(hypercompression_of_time_horizons, snare).
domain_category(ibm_shield_contract_2026, snare).
domain_category(ice_memory_archive, tangled_rope).
domain_category(ice_safe_departure, snare).
domain_category(identity_stack_incompatibility, snare).
domain_category(idf_knock_on_roof_policy, snare).
domain_category(incentive_surface_warping, snare).
domain_category(incumbent_steel_production, snare).
domain_category(independent_criticism_patronage, tangled_rope).
domain_category(indexical_extraction_asymmetry, snare).
domain_category(indexical_extraction_variance, mountain).
domain_category(indexical_power_variance, mountain).
domain_category(indexical_relativity_core, mountain).
domain_category(indexical_relativity_of_extraction, mountain).
domain_category(india_france_horizon_2047, snare).
domain_category(india_nuclear_liability_act_2010, snare).
domain_category(india_semi_mission, tangled_rope).
domain_category(indian_ai_licensing_regime, snare).
domain_category(indian_import_tariffs_eu, snare).
domain_category(individual_revolution_autonomy, snare).
domain_category(individual_vs_systemic_causation, snare).
domain_category(indo_german_defense_pact, snare).
domain_category(indo_russian_submarine_lease_2025, snare).
domain_category(indonesia_penal_code_2023, snare).
domain_category(informant_recruitment_through_false_solidarity, snare).
domain_category(information_foraging_theory, tangled_rope).
domain_category(informational_time_2026, tangled_rope).
domain_category(infrastructure_interoperability_decay, snare).
domain_category(inner_models, snare).
domain_category(innovators_dilemma, snare).
domain_category(input_specification_failure, mountain).
domain_category(institutional_framing_tangled_rope, snare).
domain_category(institutional_inertia_lock, snare).
domain_category(institutional_mandate_vs_autonomy, snare).
domain_category(institutional_memory_loss, snare).
domain_category(institutional_mutation_domestication, snare).
domain_category(institutional_mutation_without_selection, snare).
domain_category(institutional_trust_decay, snare).
domain_category(insult_wisdom_training, snare).
domain_category(integrated_digital_governance_stack, snare).
domain_category(intelligence_as_sovereignty_transfer, tangled_rope).
domain_category(interaction_explosion, snare).
domain_category(interface_contract_breakdown, snare).
domain_category(internet_archive_preservation, snare).
domain_category(internet_evolution_lifecycle, snare).
domain_category(interoperable_credential_standards, snare).
domain_category(intertemporal_responsibility_gap, snare).
domain_category(inverse_spin_valve_signature, tangled_rope).
domain_category(iran_hijab_law, snare).
domain_category(iran_mandatrophic_collapse, snare).
domain_category(iran_nuclear_deal_informal_2023, snare).
domain_category(iron_law_of_oligarchy, snare).
domain_category(irreversible_policy_commitment, snare).
domain_category(isa_education_scaffold, scaffold).
domain_category(israel_electoral_threshold, snare).
domain_category(israel_gaza_ceasefire_violation, snare).
domain_category(israel_norwegian_law, tangled_rope).
domain_category(israel_override_clause, snare).
domain_category(israel_surplus_vote_agreements, tangled_rope).
domain_category(iss_ped_ban, tangled_rope).
domain_category(it, snare).
domain_category(iterated_function_systems, tangled_rope).
domain_category(jevons_paradox, tangled_rope).
domain_category(job_hunt_volume_system_2026, snare).
domain_category(jordan_microfinance, snare).
domain_category(jp_eez_enforcement, snare).
domain_category(jupiter_composition_knowledge_gap, tangled_rope).
domain_category(juvenile_underclass_2026, snare).
domain_category(kardashev_scale_progress_narrative, snare).
domain_category(keltner_relationship_evaluation, tangled_rope).
domain_category(kidney_exchange_market, rope).
domain_category(kim_jong_un_succession, snare).
domain_category(kirby_paris_theorem, mountain).
domain_category(kjv_textual_authority, snare).
domain_category(kleene_recursion_theorem, mountain).
domain_category(knowledge_transmission_urgency, snare).
domain_category(kolmogorov_complexity, mountain).
domain_category(labor_union_dues_structure, snare).
domain_category(lagrange_multipliers, mountain).
domain_category(landscape_of_fear_2026, snare).
domain_category(large_cardinals_foundations, tangled_rope).
domain_category(latent_goal_activation, snare).
domain_category(latent_regulatory_bomb, snare).
domain_category(lcdm_hubble_tension, tangled_rope).
domain_category(legacy_system_technical_debt, snare).
domain_category(legal_formalism_overhang, tangled_rope).
domain_category(legibility_asymmetry_as_survival, rope).
domain_category(legibility_trap, snare).
domain_category(legitimacy_without_capacity, snare).
domain_category(legitimacy_without_effectiveness, snare).
domain_category(legitimation_through_objectivity, snare).
domain_category(lehman_repo_105, snare).
domain_category(liar_paradox, mountain).
domain_category(lindy_effect, tangled_rope).
domain_category(linguistic_relativity_cultural_framing, snare).
domain_category(liquidity_illusion, snare).
domain_category(litany_of_the_real, rope).
domain_category(litchfield_sensitive_locations_2026, snare).
domain_category(lln_convergence, mountain).
domain_category(lobs_theorem, mountain).
domain_category(local_vs_global_optima, mountain).
domain_category(logistic_map_dynamics, mountain).
domain_category(lorenz_attractor, mountain).
domain_category(lorenz_attractor_dynamics, mountain).
domain_category(lowenheim_skolem_theorem, mountain).
domain_category(lp_pikachu_illustrator, snare).
domain_category(lsd_microdosing_professional_openness, snare).
domain_category(lula_hemisphere_2026, snare).
domain_category(lung_transplant_protocol, snare).
domain_category(lyapunov_stability, mountain).
domain_category(magna_carta_liberties, tangled_rope).
domain_category(maha_recovery_2026, snare).
domain_category(maintenance_capacity_shortfall, snare).
domain_category(maladaptive_selection_process, snare).
domain_category(mandatrophic_margin_collapse_diagnostic, snare).
domain_category(manga_distribution_duopoly, snare).
domain_category(manganese_catalysis_2026, tangled_rope).
domain_category(marriage_market_asymmetry_2026, snare).
domain_category(mars_rovers_navigational_autonomy, mountain).
domain_category(martian_signal_latency, mountain).
domain_category(matching_markets, tangled_rope).
domain_category(material_tensile_strength, mountain).
domain_category(max_flow, snare).
domain_category(max_flow_theorem, snare).
domain_category(mco_unit_system_discontinuity, piton).
domain_category(mean_value_theorem, mountain).
domain_category(measurement_apparatus_bidirectionality, mountain).
domain_category(measurement_fidelity_as_authority_substrate, mountain).
domain_category(measurement_timing_authority_erosion, snare).
domain_category(med_diet_consensus_2026, snare).
domain_category(medical_residency_match, tangled_rope).
domain_category(medieval_church_hegemony, snare).
domain_category(memetic_fitness_vs_truth, snare).
domain_category(meritocratic_ideology_as_error_propagation, snare).
domain_category(meta_model_lock_in, snare).
domain_category(meta_nda, snare).
domain_category(meta_nuclear_power_agreement, snare).
domain_category(meta_pay_or_okay_model, snare).
domain_category(metabolic_constraint_cognition, snare).
domain_category(metamorphosis_samsa, snare).
domain_category(mexican_airline_merger, snare).
domain_category(micro_robot_electronics_integration, snare).
domain_category(microrobot_manipulation, rope).
domain_category(minimax_theorem, mountain).
domain_category(minnesota_sovereignty_2026, snare).
domain_category(mirror_of_erised_expectation, snare).
domain_category(misunderstanding_as_mismatch, snare).
domain_category(mit_tfus_consciousness_2026, snare).
domain_category(mltt_economic_model, snare).
domain_category(model_autonomy_creep, snare).
domain_category(model_collapse_feedback_loop, snare).
domain_category(model_of_models_regression, snare).
domain_category(moltbook_agent_theater, snare).
domain_category(moltbook_breach_2026, snare).
domain_category(moltbot_religion, snare).
domain_category(mom_z14_galaxy_2026, mountain).
domain_category(monetary_regime_transition, snare).
domain_category(monopoly_fp_house_rule, tangled_rope).
domain_category(monty_hall_conditional_probability, mountain).
domain_category(moores_law, snare).
domain_category(moral_clarity_paralysis, snare).
domain_category(msgs_asset_bundling, snare).
domain_category(mutual_defection_equilibrium, snare).
domain_category(mythic_scaffolding_vs_formal_fragmentation, snare).
domain_category(n26usc469_real_estate_exemption, snare).
domain_category(naming_as_control, snare).
domain_category(narcissistic_ego_maintenance, snare).
domain_category(narrative_capacity_exhaustion, snare).
domain_category(narrative_engineering_2026, snare).
domain_category(narrative_overfitting, snare).
domain_category(nash_equilibrium_coordination, rope).
domain_category(nato_arctic_defense_cooperation, snare).
domain_category(ncaa_eligibility_rules, snare).
domain_category(nds_2022_pacing_challenge, snare).
domain_category(necessary_day_job, snare).
domain_category(negative_emissions_arbitrage, snare).
domain_category(nero_imperial_expropriation, snare).
domain_category(net_zero_stabilization, snare).
domain_category(network_effects, snare).
domain_category(neurodiversity_spectrum, snare).
domain_category(new_civilizational_rope, rope).
domain_category(new_start_expiration, snare).
domain_category(news_paywall_inequality, snare).
domain_category(newtons_method_convergence, mountain).
domain_category(nfl_superbowl_halftime_exclusivity, snare).
domain_category(nfl_superbowl_marketing_regulation, snare).
domain_category(nine_day_buffer, snare).
domain_category(no_cloning_theorem, mountain).
domain_category(noethers_isomorphism_theorems, mountain).
domain_category(noethers_theorem, mountain).
domain_category(noethers_theorem_symmetry, mountain).
domain_category(non_compete_agreements, snare).
domain_category(nonstandard_arithmetic_models, mountain).
domain_category(nonstandard_models_of_arithmetic, mountain).
domain_category(norm_erosion_threshold, snare).
domain_category(north_sea_wind_grid, snare).
domain_category(notary_ink_dependency, tangled_rope).
domain_category(nsl_hk, snare).
domain_category(nuclear_site_safety_norms, snare).
domain_category(nuclear_vacuum_2026, snare).
domain_category(nursery_social_hierarchy, tangled_rope).
domain_category(nvidia_cuda_ecosystem_lockin, snare).
domain_category(ny_private_school_discount, snare).
domain_category(nyc_metrocard_art_licensing, snare).
domain_category(oc_donation_model, tangled_rope).
domain_category(olympic_legacy_curling_investment, snare).
domain_category(olympic_medal_allocation, snare).
domain_category(omega1_patches, tangled_rope).
domain_category(omelet_perfection_complexity, tangled_rope).
domain_category(ontological_friction_resolution, snare).
domain_category(open_culture_newsletter, tangled_rope).
domain_category(open_source_commons, rope).
domain_category(openai_api_access, snare).
domain_category(openai_codex_app_constraint, snare).
domain_category(openai_default_data_training, snare).
domain_category(openai_health_review, snare).
domain_category(openai_implicit_translator, snare).
domain_category(openai_prism_development, snare).
domain_category(openbsd_netiquette_protocol, tangled_rope).
domain_category(openclaw_data_lock_in, snare).
domain_category(openclaw_regulation, snare).
domain_category(openscholar_peer_review, snare).
domain_category(optimization_as_entrapment, snare).
domain_category(optimization_fragility, snare).
domain_category(orbital_data_center_2026, snare).
domain_category(oscar_campaign_spending, snare).
domain_category(other_peoples_troubles_2026, snare).
domain_category(overfitting_to_frameworks, snare).
domain_category(overton_window, snare).
domain_category(p_g_golden_pear_surveillance, snare).
domain_category(p_vs_np, tangled_rope).
domain_category(panama_canal_ports, snare).
domain_category(pancreatic_cancer_lethality_v1, mountain).
domain_category(parable_fish_turtle, snare).
domain_category(paradoxical_decompositions, snare).
domain_category(pareto_principle, tangled_rope).
domain_category(paris_municipal_reform_2026, snare).
domain_category(parkinsons_law, snare).
domain_category(participatory_observer_hypothesis, snare).
domain_category(pe_rental_market_lockin, snare).
domain_category(peano_curve_mapping, mountain).
domain_category(permissive_software_licensing, tangled_rope).
domain_category(perovskite_self_etching, snare).
domain_category(perseverance_ai_drive, rope).
domain_category(personalized_nutritional_arbitrage, snare).
domain_category(peter_principle, snare).
domain_category(pfas_regulatory_framework, snare).
domain_category(physiological_constraint_ceiling, mountain).
domain_category(pla_aerial_carrier_doctrine, snare).
domain_category(pla_loyalty_purge, snare).
domain_category(planetary_boundaries, snare).
domain_category(planetary_diet_constraint_2026, snare).
domain_category(planning_fallacy, snare).
domain_category(plastic_asphalt_mandate, snare).
domain_category(platform_app_store_duopoly, snare).
domain_category(platform_cooperativism_governance, snare).
domain_category(platonic_coparenting_decoupling, tangled_rope).
domain_category(po_investigation_protocol_bias, snare).
domain_category(poetic_verse_and_past, snare).
domain_category(poincare_conjucture, mountain).
domain_category(polar_bear_biobanking, snare).
domain_category(politeness_face_negotiation, tangled_rope).
domain_category(political_art_factional_alignment, snare).
domain_category(political_dissident_containment, snare).
domain_category(portugal_government_stability_ad, scaffold).
domain_category(portugal_polarization_threshold_2026, snare).
domain_category(portuguese_presidential_term_limits, mountain).
domain_category(postman_survival_protocol, tangled_rope).
domain_category(power_indexed_classification_variance, mountain).
domain_category(power_set, mountain).
domain_category(power_without_responsibility, snare).
domain_category(prestige_signal_inflation, snare).
domain_category(price_signal_corruption, snare).
domain_category(prime_age_male_unwork, snare).
domain_category(prime_number_theorem, mountain).
domain_category(prisoners_dilemma_equilibrium, mountain).
domain_category(private_credit_market_opacity, snare).
domain_category(private_identity_integration, tangled_rope).
domain_category(procedural_compliance_theater, snare).
domain_category(procedural_legitimacy_decay, piton).
domain_category(project_vault_2026, snare).
domain_category(project_vault_extraction_2026, snare).
domain_category(proof_of_work_consensus, snare).
domain_category(protocol_capture_tangled_rope, snare).
domain_category(protocol_drift_accumulation, snare).
domain_category(protocol_execution_impossibility, mountain).
domain_category(protocol_inversion_as_constraint_escape, snare).
domain_category(protocol_rigidity_under_unclassified_variance, rope).
domain_category(public_domain_commons, snare).
domain_category(publishing_embargo, snare).
domain_category(purity_drift_degradation, snare).
domain_category(pythagorean_theorem, mountain).
domain_category(pythagorean_theorem_geometric_constancy, mountain).
domain_category(qualified_immunity, snare).
domain_category(quantum_entanglement_protocol, snare).
domain_category(quantum_nonlocality_2026, mountain).
domain_category(quellcrist_falconer_justice, snare).
domain_category(quine_self_replication, mountain).
domain_category(quota_ratchet_asymmetry, snare).
domain_category(qwerty_vs_dvorak, tangled_rope).
domain_category(raac_school_maintenance, snare).
domain_category(ramsey_numbers, mountain).
domain_category(rare_earth_dependency, snare).
domain_category(rare_earth_export_restrictions, snare).
domain_category(rare_earth_seabed_mining, snare).
domain_category(rational_inertia_trap, snare).
domain_category(reciprocity_laws_math, mountain).
domain_category(redemption_ambiguity, tangled_rope).
domain_category(referential_substrate_absence, mountain).
domain_category(regional_military_deterrence_mideast, snare).
domain_category(regulatory_capture, snare).
domain_category(regulatory_pathway_psychedelic_therapy, snare).
domain_category(relativity_of_simultaneity, mountain).
domain_category(relativity_physical_invariance, mountain).
domain_category(rent_seeking_equilibrium, snare).
domain_category(reputation_as_distributed_enforcement, snare).
domain_category(reputational_cascade_failure, snare).
domain_category(responsibility_dilution, snare).
domain_category(responsibility_without_power, snare).
domain_category(retroactive_criminalization_of_coerced_acts, snare).
domain_category(rfc9293_state_machine, mountain).
domain_category(rices_theorem_undecidability, mountain).
domain_category(riemann_mapping_theorem, mountain).
domain_category(risk_socialization_threshold, snare).
domain_category(ritualistic_transition_scaffold, scaffold).
domain_category(rn_proteus_adoption, tangled_rope).
domain_category(robustness_vs_efficiency_tradeoff, snare).
domain_category(roc_african_exarchate, snare).
domain_category(rogers_commission_institutional_analysis, snare).
domain_category(role_capture_through_cost_asymmetry, snare).
domain_category(roman_bath_system, tangled_rope).
domain_category(roman_colosseum_games, snare).
domain_category(roman_monumental_construction, snare).
domain_category(roman_road_network, snare).
domain_category(rotation_seven_black_soil, snare).
domain_category(rotation_seven_isolation, snare).
domain_category(rotation_seven_kubo_ranking, snare).
domain_category(rotmigration_decision_threshold, snare).
domain_category(royal_navy_middle_east_withdrawal, snare).
domain_category(rules_based_international_order, snare).
domain_category(russells_paradox_self_reference, mountain).
domain_category(s1_visa, tangled_rope).
domain_category(s1_visa_judgment_sharing_agreement, snare).
domain_category(sa_renewable_price_differential, snare).
domain_category(sadhu_integrity_protocol, snare).
domain_category(sapir_whorf_hypothesis, snare).
domain_category(satellite_d2m_standard, tangled_rope).
domain_category(scam_doubt_manufacturing, snare).
domain_category(scientific_paradigm_lifecycle, snare).
domain_category(second_order_unintended_consequences, snare).
domain_category(seedance_export_restriction, snare).
domain_category(self_enforced_boundary_protocol, tangled_rope).
domain_category(self_sovereign_identity, snare).
domain_category(self_surpassing_superman, snare).
domain_category(semantic_overload_friction, snare).
domain_category(semiconductor_fabrication_chokepoint, snare).
domain_category(semiconductor_mission_2026, snare).
domain_category(shadow_pricing_failure, snare).
domain_category(shannon_entropy_limit, mountain).
domain_category(shannons_source_coding_theorem, mountain).
domain_category(shock_propagation_asymmetry, snare).
domain_category(signal_without_control, snare).
domain_category(silent_dependency_activation, snare).
domain_category(silicon_lexicon_overload, snare).
domain_category(silklink_2026, snare).
domain_category(silver_scarcity_mountain_2026, mountain).
domain_category(sk_ai_act_2026, snare).
domain_category(sk_dantongbeop, snare).
domain_category(sk_newtro_aesthetic, snare).
domain_category(skills_based_hiring, tangled_rope).
domain_category(sludge_bureaucratic_friction, snare).
domain_category(sm_addictive_design, snare).
domain_category(smartphone_ubiquity, snare).
domain_category(social_credit_architecture, snare).
domain_category(social_loafing, tangled_rope).
domain_category(social_media_participation_threshold, snare).
domain_category(social_narrative_casting, snare).
domain_category(soe_property_bailout, snare).
domain_category(solar_system_weirdness, tangled_rope).
domain_category(sorites_paradox, tangled_rope).
domain_category(sovereignty_as_arbitrage, snare).
domain_category(spain_digital_offensive_2026, snare).
domain_category(square_cube_law, mountain).
domain_category(stable_marriage_coordination, rope).
domain_category(start_treaty, snare).
domain_category(status_flattening_effect, snare).
domain_category(steinmetz_valuation_asymmetry, snare).
domain_category(stoic_logos_governance, tangled_rope).
domain_category(straight_coercion_2025, snare).
domain_category(strange_attractor_dynamics, mountain).
domain_category(strange_attractors, snare).
domain_category(strategic_deep_sea_rare_earth_mining, snare).
domain_category(streaming_bundling_mandate, snare).
domain_category(structural_extraction_without_actor, piton).
domain_category(structural_position_constraint_divergence, mountain).
domain_category(sts86_ascent_checklist, mountain).
domain_category(student_loan_default_cliff, snare).
domain_category(student_loan_interest_accrual, snare).
domain_category(sturgeons_law, tangled_rope).
domain_category(suanne_coup_of_peace, snare).
domain_category(subscription_economy_model, snare).
domain_category(substrate_as_unrecognized_archive, mountain).
domain_category(succession_crisis_as_strategic_outcome, mountain).
domain_category(superbowl_advertising_extraction, snare).
domain_category(suslin_hypothesis, mountain).
domain_category(suslin_hypothesis_undecidability, mountain).
domain_category(swift_legacy_piton, piton).
domain_category(sylow_theorems, mountain).
domain_category(sylow_theorems_group_theory, mountain).
domain_category(synthetic_data_feedback_loop, snare).
domain_category(system_reproduction_through_substitution, mountain).
domain_category(tail_risk_compression, snare).
domain_category(taiwan_existential_sovereignty, snare).
domain_category(taiwan_storm_2026, snare).
domain_category(taiwan_strait_hegemony_shift, snare).
domain_category(taiwan_university_application_system, snare).
domain_category(taliban_slavery_law_2024, snare).
domain_category(tarski_undefinability_theorem, mountain).
domain_category(teaching_horses_to_sing, snare).
domain_category(tear_gas_repression_2026, snare).
domain_category(technocratic_overreach, snare).
domain_category(technological_point_of_no_return, snare).
domain_category(temporal_scale_arbitrage, snare).
domain_category(temporal_scarcity, snare).
domain_category(terrain_inaccessibility_wheeled_vehicles, mountain).
domain_category(texas_hispanic_political_pivot, snare).
domain_category(thai_article_112_mountain, mountain).
domain_category(thai_senate_veto_2026, snare).
domain_category(the_calm_protocol_suppression, snare).
domain_category(the_churn_systemic_upheaval, snare).
domain_category(the_trivial_topology, snare).
domain_category(the_wall_procedural_barrier, snare).
domain_category(theatrical_neutrality, snare).
domain_category(thermodynamics_entropy, mountain).
domain_category(three_body_problem, mountain).
domain_category(three_body_unpredicability, mountain).
domain_category(trade_secret_law, snare).
domain_category(tragedy_of_the_commons, snare).
domain_category(trajans_bridge_lifecycle, snare).
domain_category(transformation_as_threshold_marker, snare).
domain_category(transformer_self_attention, tangled_rope).
domain_category(transient_event_detection, tangled_rope).
domain_category(traveling_salesman_problem, mountain).
domain_category(traveling_salesperson_problem, tangled_rope).
domain_category(trillion_bond_rush_2026, snare).
domain_category(trump_epa_greenhouse_gas_reversal, snare).
domain_category(trump_indian_tariffs_2026, snare).
domain_category(tsp, tangled_rope).
domain_category(twin_prime_conjecture, mountain).
domain_category(ua_mobilization_protector_cert, snare).
domain_category(udhr_1946, tangled_rope).
domain_category(uk_artist_resale_right, tangled_rope).
domain_category(uk_graduate_visa_salary_threshold, snare).
domain_category(uk_help_to_buy_scheme, snare).
domain_category(uk_hicbc_2024, snare).
domain_category(uk_necc_formation, snare).
domain_category(uk_ssp_eligibility, snare).
domain_category(uk_student_visa_dependents, snare).
domain_category(uk_unpaid_care_system, snare).
domain_category(ukr_mobilization, snare).
domain_category(ukraine_tight_gas_pilot, snare).
domain_category(ulysses_chp01, snare).
domain_category(ulysses_chp02, snare).
domain_category(ulysses_chp04, snare).
domain_category(ulysses_chp05, snare).
domain_category(ulysses_chp06, tangled_rope).
domain_category(ulysses_chp07, snare).
domain_category(ulysses_chp08, snare).
domain_category(ulysses_chp09, snare).
domain_category(ulysses_chp10, tangled_rope).
domain_category(ulysses_chp11, tangled_rope).
domain_category(ulysses_chp12, snare).
domain_category(ulysses_chp13, snare).
domain_category(ulysses_chp14, mountain).
domain_category(ulysses_chp15, snare).
domain_category(ulysses_chp16, snare).
domain_category(ulysses_chp17, tangled_rope).
domain_category(ulysses_chp18, tangled_rope).
domain_category(un_high_seas_treaty_2026, snare).
domain_category(unclos_2026, snare).
domain_category(unconditional_university_offers_uk, snare).
domain_category(uneven_risk_distribution, snare).
domain_category(unilateral_condition_control, snare).
domain_category(union_protection_underperformance, snare).
domain_category(unrequited_love_protocol, snare).
domain_category(unrwa_eviction_order, snare).
domain_category(unsanctioned_substrate_access, tangled_rope).
domain_category(us_ai_chip_export_controls, snare).
domain_category(us_canada_geopolitical_asymmetry, snare).
domain_category(us_china_chip_tariffs_v2, snare).
domain_category(us_debt_ceiling, snare).
domain_category(us_embargo_cuba, snare).
domain_category(us_employer_health_insurance, snare).
domain_category(us_foreign_policy_america_first, snare).
domain_category(us_greenland_envoy, snare).
domain_category(us_isolationism_policy_2026, snare).
domain_category(us_israel_faa_502b_nonenforcement, snare).
domain_category(us_labor_mobility, snare).
domain_category(us_legal_standard_reasonable_doubt, snare).
domain_category(us_military_recruitment_advertising, snare).
domain_category(us_sanctions_belarus_2022, snare).
domain_category(us_sanctions_icc_israel_case, snare).
domain_category(us_sanctions_moex_2024, snare).
domain_category(us_sdf_alliance_abandonment_2026, snare).
domain_category(us_two_party_duopoly, snare).
domain_category(us_usmca_china_leverage, snare).
domain_category(us_venezuela_oil_pressure, snare).
domain_category(us_venezuela_plausible_deniability_2025, snare).
domain_category(us_visa_lottery, snare).
domain_category(us_wind_project_ban_2025, snare).
domain_category(usc_26_469_passive_loss, snare).
domain_category(utopia_apocalypse_fragility, snare).
domain_category(value_alignment_drift, snare).
domain_category(value_extraction_plateau, snare).
domain_category(van_der_waerden, mountain).
domain_category(venezuela_oil_privatization_v1, snare).
domain_category(verification_bottleneck, tangled_rope).
domain_category(vertebrate_turning_point_2026, tangled_rope).
domain_category(viral_emergence_covid19_exemplar, snare).
domain_category(viral_transmission_rates, snare).
domain_category(visibility_as_incitement, snare).
domain_category(visibility_bias_governance, snare).
domain_category(vision_of_the_cross, snare).
domain_category(vns_implant_for_trd, snare).
domain_category(weierstrass_function, mountain).
domain_category(whitehead_problem_undecidability, mountain).
domain_category(wikipedia_noncommercial_model, tangled_rope).
domain_category(wikipedia_notability_requirement_2026, snare).
domain_category(winners_curse, snare).
domain_category(winter_olympics_2026, snare).
domain_category(witness_obligation_without_recipient, snare).
domain_category(working_dog_training, snare).
domain_category(world_factbook_sunset_2026, tangled_rope).
domain_category(worldscale_vlsfo_benchmark, snare).
domain_category(yangtze_fishing_ban, snare).
domain_category(yoneda_lemma, mountain).
domain_category(yt_ai_slop_incentive, snare).
domain_category(zipfs_law, mountain).
domain_category(zombie_reasoning_2026, snare).
